# Generated by Django 3.0.5 on 2020-04-21 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NonTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_fname', models.CharField(max_length=200)),
                ('n_lname', models.CharField(max_length=200)),
                ('n_bdate', models.DateField()),
                ('n_relationship', models.CharField(max_length=200)),
                ('n_position', models.CharField(max_length=200)),
                ('n_email', models.CharField(max_length=200)),
                ('n_salary', models.IntegerField()),
                ('n_datejoined', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'NonTeacher',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_fname', models.CharField(max_length=200)),
                ('s_lname', models.CharField(max_length=200)),
                ('s_bdate', models.DateField()),
                ('s_class', models.CharField(max_length=100)),
                ('s_datejoined', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_fname', models.CharField(max_length=200)),
                ('t_lname', models.CharField(max_length=200)),
                ('t_bdate', models.DateField()),
                ('n_relationship', models.CharField(max_length=200)),
                ('t_course', models.CharField(max_length=200)),
                ('t_position', models.CharField(max_length=200)),
                ('t_email', models.CharField(max_length=200)),
                ('t_salary', models.IntegerField()),
                ('t_datejoined', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_fname', models.CharField(max_length=200)),
                ('p_lname', models.CharField(max_length=200)),
                ('p_contact', models.IntegerField()),
                ('p_email', models.CharField(max_length=200)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
            ],
            options={
                'verbose_name_plural': 'Parent',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200)),
                ('c_duration', models.TimeField()),
                ('teach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher')),
            ],
            options={
                'verbose_name_plural': 'Course',
            },
        ),
    ]
