# Generated by Django 3.0.5 on 2020-04-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200421_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='c_duration',
            field=models.CharField(max_length=20),
        ),
    ]
