# Generated by Django 3.0.5 on 2020-04-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20200421_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonteacher',
            name='n_relationship',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='n_relationship',
        ),
    ]
