# Generated by Django 3.0.5 on 2020-04-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonteacher',
            name='n_bdate',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='t_bdate',
        ),
    ]
