# Generated by Django 3.0.5 on 2020-05-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20200514_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fees',
            old_name='f_stu_id',
            new_name='f_stu',
        ),
    ]
