# Generated by Django 3.0.5 on 2020-05-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20200519_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='f_class',
        ),
    ]
