from django.conf.urls import url
from django.contrib import admin
from .import views


urlpatterns = [
    url('index2', views.index2, name='index2'),
    url('login', views.login, name='login'),
    url(r'^$', views.index, name='index'),
    url('logout', views.logout, name='logout'),
    url('getfile', views.getfile, name='getfile'),
    url('file', views.file, name='file'),
    url('mail', views.mail, name='mail'),
    url('b', views.b, name='b'),
    url('pt', views.pt, name='pt'),
    url('er', views.er, name='er'),
    url('zt', views.zt, name='zt'),
    url('to', views.to, name='to'),
    url('add_stu', views.add_stu, name='add_stu'),
    url('get_stu', views.get_stu, name='get_stu'),
    url('add_tea', views.add_tea, name='add_tea'),
    url('get_tea', views.get_tea, name='get_tea'),
    url('add_non', views.add_non, name='add_non'),
    url('get_non', views.get_non, name='get_non'),
    url('add_course', views.add_course, name='add_course'),
    url('get_course', views.get_course, name='get_course'),
    url('add_parent', views.add_parent, name='add_parent'),
    url('get_parent', views.get_parent, name='get_parent'),
    url('add_fee', views.add_fee, name='add_fee'),
    url('get_fee', views.get_fee, name='get_fee'),
    url('add_admin', views.add_admin, name='add_admin'),
    url('get_admin', views.get_admin, name='get_admin'),
    url('^edit_stu/(?P<id>\d+)/$', views.edit_stu, name='edit_stu'),
    url('^delete/(?P<id>\d+)/$', views.destroy, name = 'destroy'),
    url('^delete/(?P<id>\d+)/$', views.destroy1, name = 'destroy1'),
    url('^delete/(?P<id>\d+)/$', views.destroy2, name = 'destroy2'),
    url('^delete/(?P<id>\d+)/$', views.destroy3, name = 'destroy3'),
    url('^delete/(?P<id>\d+)/$', views.destroy4, name = 'destroy4'),
    url('^delete/(?P<id>\d+)/$', views.destroy5, name = 'destroy5'),
]
